spring:
  main:
    banner-mode: off
server:
  port: 10080
logging:
  config: classpath:logback-prod.xml

ukase:
  project-root: .
  resources: classpath:/
  templates: classpath:/
  jar:
  water-mark:
    degree: 60
    size: 180
    text: Sample
    x: 350
    y: 400
---

spring:
  profiles: development
logging:
  config: classpath:logback-dev.xml

---

spring:
  profiles: test
ukase:
  resources: classpath:/
  templates: classpath:/templates/
  jar:

---

spring:
  profiles: templates-dev
ukase:
  jar: resources.zip
  resources: resources
  templates: templates
