spring:
  main:
    banner-mode: off
server:
  port: 10080
logging:
  config: classpath:logback-prod.xml

ukase:
  project-root: .
  enabled-sources:
    fs: true
    jar: true
    upload: false
  resources: classpath:/
  templates: classpath:/
  jar:
  water-mark:
    degree: 60
    size: 180
    text: Sample
    x: 350
    y: 400
  bulk:
    threads: 10
    statusCodes: false
    ttl: 60
    path: pdfs
---

spring:
  profiles: development
logging:
  config: classpath:logback-dev.xml

---

spring:
  profiles: test
ukase:
  resources: classpath:/
  templates: classpath:/templates/
  jar:
  bulk:
    threads: 10
    statusCodes: false
    ttl: 1

---

spring:
  profiles: templates-dev
ukase:
  jar: resources.zip
  resources: resources
  templates: templates
