spring:
  main:
    banner-mode: off
server:
  port: 10081
logging:
  config: classpath:logback-prod.xml

ukase:
  project-root: .
  resources: .

---

spring:
  profiles: development
logging:
  config: classpath:logback-dev.xml

---

spring:
  profiles: test
ukase:
  resources: target/test-classes/
